version: '2.4'

services:
  team-unification:
    image: robocin/ssl-unification-robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
      VNC_RESOLUTION: 1920x1080
    volumes:
      - team-unification-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-unification2:
    image: robocin/ssl-unification-robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
      VNC_RESOLUTION: 1920x1080
    volumes:
      - team-unification2-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-coach:
    image: lhcs/robocin-coach:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
      VNC_RESOLUTION: 1920x1080
    volumes:
      - team-coach-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

volumes:
  team-unification-data:
  team-unification2-data:
  team-coach-data:

networks:
  match:
  guacamole:
