version: '2.4'

services:
  team-tigers:
    image: robocupssl/ubuntu-vnc-java:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
      VNC_RESOLUTION: 1920x1080
    volumes:
      - team-tigers-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-erforce:
    image: roboticserlangen/robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-erforce-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-ubcthunderbots:
    image: ubcthunderbots/tbots-software-env:0.0.1
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-ubcthunderbots-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robocin-a:
    image: robocin/ssl-unification-robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robocin-a-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robocin-b:
    image: robocin/ssl-unification-robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robocin-b-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robofei:
    image: bollos00/robofeissl-ssl-strategy:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robofei-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-roboteamtwente:
    image: roboteamtwente/practice_tournament:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-roboteamtwente-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robodragons:
    image: sslrobodragons/robodragons-system:ubuntu20.04-robocup2021-simulation-7db95ab
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robodragons-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-src:
    image: xlq57913/robocup2021-src:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-src-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-kiks:
    image: ghcr.io/kiksworks/ssl-simulation-env:main
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-kiks-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

volumes:
  team-tigers-data:
  team-erforce-data:
  team-ubcthunderbots-data:
  team-robocin-a-data:
  team-robocin-b-data:
  team-robofei-data:
  team-roboteamtwente-data:
  team-robodragons-data:
  team-src-data:
  team-kiks-data:

networks:
  match:
  guacamole:
